package com.atguigu.mbg.mapper;

import com.atguigu.bean.Case_paid;
import java.util.List;

public interface Case_paidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int insert(Case_paid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    Case_paid selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    List<Case_paid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int updateByPrimaryKey(Case_paid record);
}