package com.atguigu.mbg.mapper;

import com.atguigu.bean.Sys_user_role_relation;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_user_role_relationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("roleId") String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int insert(Sys_user_role_relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    List<Sys_user_role_relation> selectAll();
}