package com.atguigu.mbg.mapper;

import com.atguigu.bean.Sys_role_resource_relation;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_role_resource_relationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int deleteByPrimaryKey(@Param("roleId") String roleId, @Param("resourceId") String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    int insert(Sys_role_resource_relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    List<Sys_role_resource_relation> selectAll();
}