package com.atguigu.bean;

import java.util.Date;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.age
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.area_id1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String areaId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.area_id2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String areaId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.area_id3
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String areaId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.adr_cat
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String adrCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.check_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer checkApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.mail_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer mailApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.vis_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer visApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.vis_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer visCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.mail_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer mailCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.isnew
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer isnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.source
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.status
     *
     * @return the value of address.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.status
     *
     * @param status the value for address.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.name
     *
     * @return the value of address.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.name
     *
     * @param name the value for address.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.sex
     *
     * @return the value of address.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.sex
     *
     * @param sex the value for address.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.age
     *
     * @return the value of address.age
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.age
     *
     * @param age the value for address.age
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.area_id1
     *
     * @return the value of address.area_id1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAreaId1() {
        return areaId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.area_id1
     *
     * @param areaId1 the value for address.area_id1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAreaId1(String areaId1) {
        this.areaId1 = areaId1 == null ? null : areaId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.area_id2
     *
     * @return the value of address.area_id2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAreaId2() {
        return areaId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.area_id2
     *
     * @param areaId2 the value for address.area_id2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAreaId2(String areaId2) {
        this.areaId2 = areaId2 == null ? null : areaId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.area_id3
     *
     * @return the value of address.area_id3
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAreaId3() {
        return areaId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.area_id3
     *
     * @param areaId3 the value for address.area_id3
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAreaId3(String areaId3) {
        this.areaId3 = areaId3 == null ? null : areaId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.case_id
     *
     * @return the value of address.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.case_id
     *
     * @param caseId the value for address.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.adr_cat
     *
     * @return the value of address.adr_cat
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAdrCat() {
        return adrCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.adr_cat
     *
     * @param adrCat the value for address.adr_cat
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAdrCat(String adrCat) {
        this.adrCat = adrCat == null ? null : adrCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.check_app
     *
     * @return the value of address.check_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getCheckApp() {
        return checkApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.check_app
     *
     * @param checkApp the value for address.check_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCheckApp(Integer checkApp) {
        this.checkApp = checkApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.mail_app
     *
     * @return the value of address.mail_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getMailApp() {
        return mailApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.mail_app
     *
     * @param mailApp the value for address.mail_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setMailApp(Integer mailApp) {
        this.mailApp = mailApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.vis_app
     *
     * @return the value of address.vis_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVisApp() {
        return visApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.vis_app
     *
     * @param visApp the value for address.vis_app
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisApp(Integer visApp) {
        this.visApp = visApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.relation
     *
     * @return the value of address.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.relation
     *
     * @param relation the value for address.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.vis_count
     *
     * @return the value of address.vis_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVisCount() {
        return visCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.vis_count
     *
     * @param visCount the value for address.vis_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisCount(Integer visCount) {
        this.visCount = visCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.mail_count
     *
     * @return the value of address.mail_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getMailCount() {
        return mailCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.mail_count
     *
     * @param mailCount the value for address.mail_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setMailCount(Integer mailCount) {
        this.mailCount = mailCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.isnew
     *
     * @return the value of address.isnew
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.isnew
     *
     * @param isnew the value for address.isnew
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setIsnew(Integer isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.create_emp_id
     *
     * @return the value of address.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.create_emp_id
     *
     * @param createEmpId the value for address.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.create_time
     *
     * @return the value of address.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.create_time
     *
     * @param createTime the value for address.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.source
     *
     * @return the value of address.source
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.source
     *
     * @param source the value for address.source
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.remark
     *
     * @return the value of address.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.remark
     *
     * @param remark the value for address.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}