package com.atguigu.bean;

import java.util.Date;

public class Case_linkman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.mobile
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.phone_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String phoneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.phone_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer phoneCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.card_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.unit_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.unit_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String unitPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.family_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String familyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.position
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.source
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_linkman.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.id
     *
     * @return the value of case_linkman.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.id
     *
     * @param id the value for case_linkman.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.case_id
     *
     * @return the value of case_linkman.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.case_id
     *
     * @param caseId the value for case_linkman.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.name
     *
     * @return the value of case_linkman.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.name
     *
     * @param name the value for case_linkman.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.mobile
     *
     * @return the value of case_linkman.mobile
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.mobile
     *
     * @param mobile the value for case_linkman.mobile
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.phone
     *
     * @return the value of case_linkman.phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.phone
     *
     * @param phone the value for case_linkman.phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.phone_type
     *
     * @return the value of case_linkman.phone_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.phone_type
     *
     * @param phoneType the value for case_linkman.phone_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType == null ? null : phoneType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.phone_count
     *
     * @return the value of case_linkman.phone_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getPhoneCount() {
        return phoneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.phone_count
     *
     * @param phoneCount the value for case_linkman.phone_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPhoneCount(Integer phoneCount) {
        this.phoneCount = phoneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.card_no
     *
     * @return the value of case_linkman.card_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.card_no
     *
     * @param cardNo the value for case_linkman.card_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.unit_name
     *
     * @return the value of case_linkman.unit_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.unit_name
     *
     * @param unitName the value for case_linkman.unit_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.unit_phone
     *
     * @return the value of case_linkman.unit_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getUnitPhone() {
        return unitPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.unit_phone
     *
     * @param unitPhone the value for case_linkman.unit_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setUnitPhone(String unitPhone) {
        this.unitPhone = unitPhone == null ? null : unitPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.family_phone
     *
     * @return the value of case_linkman.family_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getFamilyPhone() {
        return familyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.family_phone
     *
     * @param familyPhone the value for case_linkman.family_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setFamilyPhone(String familyPhone) {
        this.familyPhone = familyPhone == null ? null : familyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.create_time
     *
     * @return the value of case_linkman.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.create_time
     *
     * @param createTime the value for case_linkman.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.create_emp_id
     *
     * @return the value of case_linkman.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.create_emp_id
     *
     * @param createEmpId the value for case_linkman.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.status
     *
     * @return the value of case_linkman.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.status
     *
     * @param status the value for case_linkman.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.position
     *
     * @return the value of case_linkman.position
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.position
     *
     * @param position the value for case_linkman.position
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.relation
     *
     * @return the value of case_linkman.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.relation
     *
     * @param relation the value for case_linkman.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.version
     *
     * @return the value of case_linkman.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.version
     *
     * @param version the value for case_linkman.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.source
     *
     * @return the value of case_linkman.source
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.source
     *
     * @param source the value for case_linkman.source
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.address
     *
     * @return the value of case_linkman.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.address
     *
     * @param address the value for case_linkman.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_linkman.remark
     *
     * @return the value of case_linkman.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_linkman.remark
     *
     * @param remark the value for case_linkman.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}