package com.atguigu.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Case_paid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.ptp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date ptpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.ptp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal ptpMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date cpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal cpMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.paid_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date paidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.paid_num
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal paidNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.sur_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String surUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.sur_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date surTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.del_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String delUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.del_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date delTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.m_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal mPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cpm_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal cpmPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.se_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String seNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cm_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal cmPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.back_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal backPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.back_paid_rate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal backPaidRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.pback_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal pbackPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.entrust_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal entrustPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.entrust_paid_rate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal entrustPaidRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.last_debt_m
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal lastDebtM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.left_amt
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal leftAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String modifyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.is_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String isDerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.in_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal inDerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.out_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal outDerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cancel_reason
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.repay_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.operate_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String operateEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.operate_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.sur_remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String surRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.id
     *
     * @return the value of case_paid.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.id
     *
     * @param id the value for case_paid.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.state
     *
     * @return the value of case_paid.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.state
     *
     * @param state the value for case_paid.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.case_id
     *
     * @return the value of case_paid.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.case_id
     *
     * @param caseId the value for case_paid.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.ptp_time
     *
     * @return the value of case_paid.ptp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getPtpTime() {
        return ptpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.ptp_time
     *
     * @param ptpTime the value for case_paid.ptp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPtpTime(Date ptpTime) {
        this.ptpTime = ptpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.ptp_money
     *
     * @return the value of case_paid.ptp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getPtpMoney() {
        return ptpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.ptp_money
     *
     * @param ptpMoney the value for case_paid.ptp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPtpMoney(BigDecimal ptpMoney) {
        this.ptpMoney = ptpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cp_time
     *
     * @return the value of case_paid.cp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCpTime() {
        return cpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cp_time
     *
     * @param cpTime the value for case_paid.cp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCpTime(Date cpTime) {
        this.cpTime = cpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cp_money
     *
     * @return the value of case_paid.cp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getCpMoney() {
        return cpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cp_money
     *
     * @param cpMoney the value for case_paid.cp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCpMoney(BigDecimal cpMoney) {
        this.cpMoney = cpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.paid_time
     *
     * @return the value of case_paid.paid_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.paid_time
     *
     * @param paidTime the value for case_paid.paid_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.paid_num
     *
     * @return the value of case_paid.paid_num
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getPaidNum() {
        return paidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.paid_num
     *
     * @param paidNum the value for case_paid.paid_num
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPaidNum(BigDecimal paidNum) {
        this.paidNum = paidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.sur_user
     *
     * @return the value of case_paid.sur_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSurUser() {
        return surUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.sur_user
     *
     * @param surUser the value for case_paid.sur_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSurUser(String surUser) {
        this.surUser = surUser == null ? null : surUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.sur_time
     *
     * @return the value of case_paid.sur_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getSurTime() {
        return surTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.sur_time
     *
     * @param surTime the value for case_paid.sur_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSurTime(Date surTime) {
        this.surTime = surTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.del_user
     *
     * @return the value of case_paid.del_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getDelUser() {
        return delUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.del_user
     *
     * @param delUser the value for case_paid.del_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setDelUser(String delUser) {
        this.delUser = delUser == null ? null : delUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.del_time
     *
     * @return the value of case_paid.del_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.del_time
     *
     * @param delTime the value for case_paid.del_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.m_paid
     *
     * @return the value of case_paid.m_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getmPaid() {
        return mPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.m_paid
     *
     * @param mPaid the value for case_paid.m_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setmPaid(BigDecimal mPaid) {
        this.mPaid = mPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cpm_paid
     *
     * @return the value of case_paid.cpm_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getCpmPaid() {
        return cpmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cpm_paid
     *
     * @param cpmPaid the value for case_paid.cpm_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCpmPaid(BigDecimal cpmPaid) {
        this.cpmPaid = cpmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.se_no
     *
     * @return the value of case_paid.se_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSeNo() {
        return seNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.se_no
     *
     * @param seNo the value for case_paid.se_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSeNo(String seNo) {
        this.seNo = seNo == null ? null : seNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cm_paid
     *
     * @return the value of case_paid.cm_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getCmPaid() {
        return cmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cm_paid
     *
     * @param cmPaid the value for case_paid.cm_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCmPaid(BigDecimal cmPaid) {
        this.cmPaid = cmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.back_paid
     *
     * @return the value of case_paid.back_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getBackPaid() {
        return backPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.back_paid
     *
     * @param backPaid the value for case_paid.back_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setBackPaid(BigDecimal backPaid) {
        this.backPaid = backPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.back_paid_rate
     *
     * @return the value of case_paid.back_paid_rate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getBackPaidRate() {
        return backPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.back_paid_rate
     *
     * @param backPaidRate the value for case_paid.back_paid_rate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setBackPaidRate(BigDecimal backPaidRate) {
        this.backPaidRate = backPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.pback_paid
     *
     * @return the value of case_paid.pback_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getPbackPaid() {
        return pbackPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.pback_paid
     *
     * @param pbackPaid the value for case_paid.pback_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPbackPaid(BigDecimal pbackPaid) {
        this.pbackPaid = pbackPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.entrust_paid
     *
     * @return the value of case_paid.entrust_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getEntrustPaid() {
        return entrustPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.entrust_paid
     *
     * @param entrustPaid the value for case_paid.entrust_paid
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setEntrustPaid(BigDecimal entrustPaid) {
        this.entrustPaid = entrustPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.entrust_paid_rate
     *
     * @return the value of case_paid.entrust_paid_rate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getEntrustPaidRate() {
        return entrustPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.entrust_paid_rate
     *
     * @param entrustPaidRate the value for case_paid.entrust_paid_rate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setEntrustPaidRate(BigDecimal entrustPaidRate) {
        this.entrustPaidRate = entrustPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.last_debt_m
     *
     * @return the value of case_paid.last_debt_m
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getLastDebtM() {
        return lastDebtM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.last_debt_m
     *
     * @param lastDebtM the value for case_paid.last_debt_m
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setLastDebtM(BigDecimal lastDebtM) {
        this.lastDebtM = lastDebtM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.left_amt
     *
     * @return the value of case_paid.left_amt
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getLeftAmt() {
        return leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.left_amt
     *
     * @param leftAmt the value for case_paid.left_amt
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setLeftAmt(BigDecimal leftAmt) {
        this.leftAmt = leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.create_emp_id
     *
     * @return the value of case_paid.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.create_emp_id
     *
     * @param createEmpId the value for case_paid.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.create_time
     *
     * @return the value of case_paid.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.create_time
     *
     * @param createTime the value for case_paid.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.modify_emp_id
     *
     * @return the value of case_paid.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.modify_emp_id
     *
     * @param modifyEmpId the value for case_paid.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyEmpId(String modifyEmpId) {
        this.modifyEmpId = modifyEmpId == null ? null : modifyEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.modify_time
     *
     * @return the value of case_paid.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.modify_time
     *
     * @param modifyTime the value for case_paid.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.version
     *
     * @return the value of case_paid.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.version
     *
     * @param version the value for case_paid.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.is_derate
     *
     * @return the value of case_paid.is_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getIsDerate() {
        return isDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.is_derate
     *
     * @param isDerate the value for case_paid.is_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setIsDerate(String isDerate) {
        this.isDerate = isDerate == null ? null : isDerate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.in_derate
     *
     * @return the value of case_paid.in_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getInDerate() {
        return inDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.in_derate
     *
     * @param inDerate the value for case_paid.in_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setInDerate(BigDecimal inDerate) {
        this.inDerate = inDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.out_derate
     *
     * @return the value of case_paid.out_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getOutDerate() {
        return outDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.out_derate
     *
     * @param outDerate the value for case_paid.out_derate
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setOutDerate(BigDecimal outDerate) {
        this.outDerate = outDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cancel_reason
     *
     * @return the value of case_paid.cancel_reason
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cancel_reason
     *
     * @param cancelReason the value for case_paid.cancel_reason
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.repay_type
     *
     * @return the value of case_paid.repay_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.repay_type
     *
     * @param repayType the value for case_paid.repay_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRepayType(String repayType) {
        this.repayType = repayType == null ? null : repayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.operate_emp_id
     *
     * @return the value of case_paid.operate_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getOperateEmpId() {
        return operateEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.operate_emp_id
     *
     * @param operateEmpId the value for case_paid.operate_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setOperateEmpId(String operateEmpId) {
        this.operateEmpId = operateEmpId == null ? null : operateEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.operate_time
     *
     * @return the value of case_paid.operate_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.operate_time
     *
     * @param operateTime the value for case_paid.operate_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.sur_remark
     *
     * @return the value of case_paid.sur_remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSurRemark() {
        return surRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.sur_remark
     *
     * @param surRemark the value for case_paid.sur_remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSurRemark(String surRemark) {
        this.surRemark = surRemark == null ? null : surRemark.trim();
    }
}