package com.atguigu.bean;

import java.util.Date;

public class Case_apply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.apply_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.ch_cat_1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String chCat1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.ch_cat_2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String chCat2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.address_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.msg_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer msgState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.apply_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String applyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.apply_user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String applyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.sur_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String surUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.sur_user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String surUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.app_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date appTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.sur_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date surTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.contact_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String contactUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.ch_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer chCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.approval_opinion
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String approvalOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.mail_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date mailTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.apply_content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String applyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.hurry_content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String hurryContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.id
     *
     * @return the value of case_apply.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.id
     *
     * @param id the value for case_apply.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.state
     *
     * @return the value of case_apply.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.state
     *
     * @param state the value for case_apply.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.apply_type
     *
     * @return the value of case_apply.apply_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.apply_type
     *
     * @param applyType the value for case_apply.apply_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyType(Integer applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.ch_cat_1
     *
     * @return the value of case_apply.ch_cat_1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getChCat1() {
        return chCat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.ch_cat_1
     *
     * @param chCat1 the value for case_apply.ch_cat_1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setChCat1(String chCat1) {
        this.chCat1 = chCat1 == null ? null : chCat1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.ch_cat_2
     *
     * @return the value of case_apply.ch_cat_2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getChCat2() {
        return chCat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.ch_cat_2
     *
     * @param chCat2 the value for case_apply.ch_cat_2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setChCat2(String chCat2) {
        this.chCat2 = chCat2 == null ? null : chCat2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.address_id
     *
     * @return the value of case_apply.address_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.address_id
     *
     * @param addressId the value for case_apply.address_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.msg_state
     *
     * @return the value of case_apply.msg_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getMsgState() {
        return msgState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.msg_state
     *
     * @param msgState the value for case_apply.msg_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setMsgState(Integer msgState) {
        this.msgState = msgState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.case_id
     *
     * @return the value of case_apply.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.case_id
     *
     * @param caseId the value for case_apply.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.apply_user
     *
     * @return the value of case_apply.apply_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApplyUser() {
        return applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.apply_user
     *
     * @param applyUser the value for case_apply.apply_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser == null ? null : applyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.apply_user_name
     *
     * @return the value of case_apply.apply_user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApplyUserName() {
        return applyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.apply_user_name
     *
     * @param applyUserName the value for case_apply.apply_user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyUserName(String applyUserName) {
        this.applyUserName = applyUserName == null ? null : applyUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.sur_user
     *
     * @return the value of case_apply.sur_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSurUser() {
        return surUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.sur_user
     *
     * @param surUser the value for case_apply.sur_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSurUser(String surUser) {
        this.surUser = surUser == null ? null : surUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.sur_user_name
     *
     * @return the value of case_apply.sur_user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSurUserName() {
        return surUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.sur_user_name
     *
     * @param surUserName the value for case_apply.sur_user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSurUserName(String surUserName) {
        this.surUserName = surUserName == null ? null : surUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.app_time
     *
     * @return the value of case_apply.app_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.app_time
     *
     * @param appTime the value for case_apply.app_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.sur_time
     *
     * @return the value of case_apply.sur_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getSurTime() {
        return surTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.sur_time
     *
     * @param surTime the value for case_apply.sur_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSurTime(Date surTime) {
        this.surTime = surTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.contact_user
     *
     * @return the value of case_apply.contact_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getContactUser() {
        return contactUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.contact_user
     *
     * @param contactUser the value for case_apply.contact_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setContactUser(String contactUser) {
        this.contactUser = contactUser == null ? null : contactUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.address
     *
     * @return the value of case_apply.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.address
     *
     * @param address the value for case_apply.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.ch_count
     *
     * @return the value of case_apply.ch_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getChCount() {
        return chCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.ch_count
     *
     * @param chCount the value for case_apply.ch_count
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setChCount(Integer chCount) {
        this.chCount = chCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.approval_opinion
     *
     * @return the value of case_apply.approval_opinion
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApprovalOpinion() {
        return approvalOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.approval_opinion
     *
     * @param approvalOpinion the value for case_apply.approval_opinion
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApprovalOpinion(String approvalOpinion) {
        this.approvalOpinion = approvalOpinion == null ? null : approvalOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.mail_time
     *
     * @return the value of case_apply.mail_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getMailTime() {
        return mailTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.mail_time
     *
     * @param mailTime the value for case_apply.mail_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setMailTime(Date mailTime) {
        this.mailTime = mailTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.apply_content
     *
     * @return the value of case_apply.apply_content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApplyContent() {
        return applyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.apply_content
     *
     * @param applyContent the value for case_apply.apply_content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent == null ? null : applyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.hurry_content
     *
     * @return the value of case_apply.hurry_content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getHurryContent() {
        return hurryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.hurry_content
     *
     * @param hurryContent the value for case_apply.hurry_content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setHurryContent(String hurryContent) {
        this.hurryContent = hurryContent == null ? null : hurryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply.remark
     *
     * @return the value of case_apply.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply.remark
     *
     * @param remark the value for case_apply.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}