package com.atguigu.bean;

import java.util.Date;

public class Employee_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.salt
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.number
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.personal_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String personalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.birthday
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.nation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.password
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.login_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.married
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Boolean married;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.province
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.city
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.email
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.join_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.position_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.org_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_login
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String ccLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_pwd
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String ccPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_server
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String ccServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String ccPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.contact_mode
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String contactMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.attach_org_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String attachOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.attach_entrust_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String attachEntrustId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.id
     *
     * @return the value of employee_info.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.id
     *
     * @param id the value for employee_info.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.salt
     *
     * @return the value of employee_info.salt
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.salt
     *
     * @param salt the value for employee_info.salt
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.create_time
     *
     * @return the value of employee_info.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.create_time
     *
     * @param createTime the value for employee_info.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.modify_time
     *
     * @return the value of employee_info.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.modify_time
     *
     * @param modifyTime the value for employee_info.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.version
     *
     * @return the value of employee_info.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.version
     *
     * @param version the value for employee_info.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.number
     *
     * @return the value of employee_info.number
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.number
     *
     * @param number the value for employee_info.number
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.status
     *
     * @return the value of employee_info.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.status
     *
     * @param status the value for employee_info.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.user_name
     *
     * @return the value of employee_info.user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.user_name
     *
     * @param userName the value for employee_info.user_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.personal_id
     *
     * @return the value of employee_info.personal_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPersonalId() {
        return personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.personal_id
     *
     * @param personalId the value for employee_info.personal_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPersonalId(String personalId) {
        this.personalId = personalId == null ? null : personalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.sex
     *
     * @return the value of employee_info.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.sex
     *
     * @param sex the value for employee_info.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.birthday
     *
     * @return the value of employee_info.birthday
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.birthday
     *
     * @param birthday the value for employee_info.birthday
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.nation
     *
     * @return the value of employee_info.nation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.nation
     *
     * @param nation the value for employee_info.nation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.password
     *
     * @return the value of employee_info.password
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.password
     *
     * @param password the value for employee_info.password
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.login_name
     *
     * @return the value of employee_info.login_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.login_name
     *
     * @param loginName the value for employee_info.login_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.married
     *
     * @return the value of employee_info.married
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Boolean getMarried() {
        return married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.married
     *
     * @param married the value for employee_info.married
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setMarried(Boolean married) {
        this.married = married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.province
     *
     * @return the value of employee_info.province
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.province
     *
     * @param province the value for employee_info.province
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.city
     *
     * @return the value of employee_info.city
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.city
     *
     * @param city the value for employee_info.city
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.email
     *
     * @return the value of employee_info.email
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.email
     *
     * @param email the value for employee_info.email
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.join_time
     *
     * @return the value of employee_info.join_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.join_time
     *
     * @param joinTime the value for employee_info.join_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.position_id
     *
     * @return the value of employee_info.position_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.position_id
     *
     * @param positionId the value for employee_info.position_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId == null ? null : positionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.org_id
     *
     * @return the value of employee_info.org_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.org_id
     *
     * @param orgId the value for employee_info.org_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_login
     *
     * @return the value of employee_info.cc_login
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCcLogin() {
        return ccLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_login
     *
     * @param ccLogin the value for employee_info.cc_login
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCcLogin(String ccLogin) {
        this.ccLogin = ccLogin == null ? null : ccLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_pwd
     *
     * @return the value of employee_info.cc_pwd
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCcPwd() {
        return ccPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_pwd
     *
     * @param ccPwd the value for employee_info.cc_pwd
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCcPwd(String ccPwd) {
        this.ccPwd = ccPwd == null ? null : ccPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_server
     *
     * @return the value of employee_info.cc_server
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCcServer() {
        return ccServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_server
     *
     * @param ccServer the value for employee_info.cc_server
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCcServer(String ccServer) {
        this.ccServer = ccServer == null ? null : ccServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_phone
     *
     * @return the value of employee_info.cc_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCcPhone() {
        return ccPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_phone
     *
     * @param ccPhone the value for employee_info.cc_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCcPhone(String ccPhone) {
        this.ccPhone = ccPhone == null ? null : ccPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.contact_mode
     *
     * @return the value of employee_info.contact_mode
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getContactMode() {
        return contactMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.contact_mode
     *
     * @param contactMode the value for employee_info.contact_mode
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setContactMode(String contactMode) {
        this.contactMode = contactMode == null ? null : contactMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.attach_org_id
     *
     * @return the value of employee_info.attach_org_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAttachOrgId() {
        return attachOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.attach_org_id
     *
     * @param attachOrgId the value for employee_info.attach_org_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAttachOrgId(String attachOrgId) {
        this.attachOrgId = attachOrgId == null ? null : attachOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.attach_entrust_id
     *
     * @return the value of employee_info.attach_entrust_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAttachEntrustId() {
        return attachEntrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.attach_entrust_id
     *
     * @param attachEntrustId the value for employee_info.attach_entrust_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAttachEntrustId(String attachEntrustId) {
        this.attachEntrustId = attachEntrustId == null ? null : attachEntrustId.trim();
    }
}