package com.atguigu.bean;

import java.util.Date;

public class Entrust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.code
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.cooperate_date
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date cooperateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.service_hotline
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String serviceHotline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.abutment_person
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String abutmentPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.abutment_email
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String abutmentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.abutment_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String abutmentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.case_frequency
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.effec_repay_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String effecRepayPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.collec_nominal
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String collecNominal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.collec_term
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String collecTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.stay_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String stayRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.back_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String backRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.report_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String reportPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.settlement_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String settlementPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.repayment_method
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String repaymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.discount_reduction
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String discountReduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.period_repayment_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String periodRepaymentRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.cancel_account
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String cancelAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.resource_retrieve_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String resourceRetrieveRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.collec_submit_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String collecSubmitRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.complaint_handle_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String complaintHandleRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.tape_submit_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String tapeSubmitRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.data_destruc_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String dataDestrucRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.letter_recovery_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String letterRecoveryRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.report_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String reportRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.cus_special_instruc
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String cusSpecialInstruc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.contract_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.create_emp_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.case_type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.product_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.id
     *
     * @return the value of entrust.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.id
     *
     * @param id the value for entrust.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.name
     *
     * @return the value of entrust.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.name
     *
     * @param name the value for entrust.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.code
     *
     * @return the value of entrust.code
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.code
     *
     * @param code the value for entrust.code
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.cooperate_date
     *
     * @return the value of entrust.cooperate_date
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCooperateDate() {
        return cooperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.cooperate_date
     *
     * @param cooperateDate the value for entrust.cooperate_date
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCooperateDate(Date cooperateDate) {
        this.cooperateDate = cooperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.address
     *
     * @return the value of entrust.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.address
     *
     * @param address the value for entrust.address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.service_hotline
     *
     * @return the value of entrust.service_hotline
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getServiceHotline() {
        return serviceHotline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.service_hotline
     *
     * @param serviceHotline the value for entrust.service_hotline
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setServiceHotline(String serviceHotline) {
        this.serviceHotline = serviceHotline == null ? null : serviceHotline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.abutment_person
     *
     * @return the value of entrust.abutment_person
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAbutmentPerson() {
        return abutmentPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.abutment_person
     *
     * @param abutmentPerson the value for entrust.abutment_person
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAbutmentPerson(String abutmentPerson) {
        this.abutmentPerson = abutmentPerson == null ? null : abutmentPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.abutment_email
     *
     * @return the value of entrust.abutment_email
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAbutmentEmail() {
        return abutmentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.abutment_email
     *
     * @param abutmentEmail the value for entrust.abutment_email
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAbutmentEmail(String abutmentEmail) {
        this.abutmentEmail = abutmentEmail == null ? null : abutmentEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.abutment_phone
     *
     * @return the value of entrust.abutment_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAbutmentPhone() {
        return abutmentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.abutment_phone
     *
     * @param abutmentPhone the value for entrust.abutment_phone
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAbutmentPhone(String abutmentPhone) {
        this.abutmentPhone = abutmentPhone == null ? null : abutmentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.case_frequency
     *
     * @return the value of entrust.case_frequency
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseFrequency() {
        return caseFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.case_frequency
     *
     * @param caseFrequency the value for entrust.case_frequency
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseFrequency(String caseFrequency) {
        this.caseFrequency = caseFrequency == null ? null : caseFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.effec_repay_period
     *
     * @return the value of entrust.effec_repay_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getEffecRepayPeriod() {
        return effecRepayPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.effec_repay_period
     *
     * @param effecRepayPeriod the value for entrust.effec_repay_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setEffecRepayPeriod(String effecRepayPeriod) {
        this.effecRepayPeriod = effecRepayPeriod == null ? null : effecRepayPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.collec_nominal
     *
     * @return the value of entrust.collec_nominal
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCollecNominal() {
        return collecNominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.collec_nominal
     *
     * @param collecNominal the value for entrust.collec_nominal
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCollecNominal(String collecNominal) {
        this.collecNominal = collecNominal == null ? null : collecNominal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.collec_term
     *
     * @return the value of entrust.collec_term
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCollecTerm() {
        return collecTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.collec_term
     *
     * @param collecTerm the value for entrust.collec_term
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCollecTerm(String collecTerm) {
        this.collecTerm = collecTerm == null ? null : collecTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.stay_require
     *
     * @return the value of entrust.stay_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getStayRequire() {
        return stayRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.stay_require
     *
     * @param stayRequire the value for entrust.stay_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setStayRequire(String stayRequire) {
        this.stayRequire = stayRequire == null ? null : stayRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.back_require
     *
     * @return the value of entrust.back_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getBackRequire() {
        return backRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.back_require
     *
     * @param backRequire the value for entrust.back_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setBackRequire(String backRequire) {
        this.backRequire = backRequire == null ? null : backRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.report_period
     *
     * @return the value of entrust.report_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getReportPeriod() {
        return reportPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.report_period
     *
     * @param reportPeriod the value for entrust.report_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setReportPeriod(String reportPeriod) {
        this.reportPeriod = reportPeriod == null ? null : reportPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.settlement_period
     *
     * @return the value of entrust.settlement_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSettlementPeriod() {
        return settlementPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.settlement_period
     *
     * @param settlementPeriod the value for entrust.settlement_period
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSettlementPeriod(String settlementPeriod) {
        this.settlementPeriod = settlementPeriod == null ? null : settlementPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.repayment_method
     *
     * @return the value of entrust.repayment_method
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRepaymentMethod() {
        return repaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.repayment_method
     *
     * @param repaymentMethod the value for entrust.repayment_method
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRepaymentMethod(String repaymentMethod) {
        this.repaymentMethod = repaymentMethod == null ? null : repaymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.discount_reduction
     *
     * @return the value of entrust.discount_reduction
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getDiscountReduction() {
        return discountReduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.discount_reduction
     *
     * @param discountReduction the value for entrust.discount_reduction
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setDiscountReduction(String discountReduction) {
        this.discountReduction = discountReduction == null ? null : discountReduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.period_repayment_require
     *
     * @return the value of entrust.period_repayment_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPeriodRepaymentRequire() {
        return periodRepaymentRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.period_repayment_require
     *
     * @param periodRepaymentRequire the value for entrust.period_repayment_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPeriodRepaymentRequire(String periodRepaymentRequire) {
        this.periodRepaymentRequire = periodRepaymentRequire == null ? null : periodRepaymentRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.cancel_account
     *
     * @return the value of entrust.cancel_account
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCancelAccount() {
        return cancelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.cancel_account
     *
     * @param cancelAccount the value for entrust.cancel_account
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCancelAccount(String cancelAccount) {
        this.cancelAccount = cancelAccount == null ? null : cancelAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.resource_retrieve_require
     *
     * @return the value of entrust.resource_retrieve_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getResourceRetrieveRequire() {
        return resourceRetrieveRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.resource_retrieve_require
     *
     * @param resourceRetrieveRequire the value for entrust.resource_retrieve_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setResourceRetrieveRequire(String resourceRetrieveRequire) {
        this.resourceRetrieveRequire = resourceRetrieveRequire == null ? null : resourceRetrieveRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.collec_submit_require
     *
     * @return the value of entrust.collec_submit_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCollecSubmitRequire() {
        return collecSubmitRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.collec_submit_require
     *
     * @param collecSubmitRequire the value for entrust.collec_submit_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCollecSubmitRequire(String collecSubmitRequire) {
        this.collecSubmitRequire = collecSubmitRequire == null ? null : collecSubmitRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.complaint_handle_require
     *
     * @return the value of entrust.complaint_handle_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getComplaintHandleRequire() {
        return complaintHandleRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.complaint_handle_require
     *
     * @param complaintHandleRequire the value for entrust.complaint_handle_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setComplaintHandleRequire(String complaintHandleRequire) {
        this.complaintHandleRequire = complaintHandleRequire == null ? null : complaintHandleRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.tape_submit_require
     *
     * @return the value of entrust.tape_submit_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getTapeSubmitRequire() {
        return tapeSubmitRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.tape_submit_require
     *
     * @param tapeSubmitRequire the value for entrust.tape_submit_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setTapeSubmitRequire(String tapeSubmitRequire) {
        this.tapeSubmitRequire = tapeSubmitRequire == null ? null : tapeSubmitRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.data_destruc_require
     *
     * @return the value of entrust.data_destruc_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getDataDestrucRequire() {
        return dataDestrucRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.data_destruc_require
     *
     * @param dataDestrucRequire the value for entrust.data_destruc_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setDataDestrucRequire(String dataDestrucRequire) {
        this.dataDestrucRequire = dataDestrucRequire == null ? null : dataDestrucRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.letter_recovery_require
     *
     * @return the value of entrust.letter_recovery_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getLetterRecoveryRequire() {
        return letterRecoveryRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.letter_recovery_require
     *
     * @param letterRecoveryRequire the value for entrust.letter_recovery_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setLetterRecoveryRequire(String letterRecoveryRequire) {
        this.letterRecoveryRequire = letterRecoveryRequire == null ? null : letterRecoveryRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.report_require
     *
     * @return the value of entrust.report_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getReportRequire() {
        return reportRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.report_require
     *
     * @param reportRequire the value for entrust.report_require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setReportRequire(String reportRequire) {
        this.reportRequire = reportRequire == null ? null : reportRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.cus_special_instruc
     *
     * @return the value of entrust.cus_special_instruc
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCusSpecialInstruc() {
        return cusSpecialInstruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.cus_special_instruc
     *
     * @param cusSpecialInstruc the value for entrust.cus_special_instruc
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCusSpecialInstruc(String cusSpecialInstruc) {
        this.cusSpecialInstruc = cusSpecialInstruc == null ? null : cusSpecialInstruc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.state
     *
     * @return the value of entrust.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.state
     *
     * @param state the value for entrust.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.modify_time
     *
     * @return the value of entrust.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.modify_time
     *
     * @param modifyTime the value for entrust.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.contract_name
     *
     * @return the value of entrust.contract_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.contract_name
     *
     * @param contractName the value for entrust.contract_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.create_emp_id
     *
     * @return the value of entrust.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.create_emp_id
     *
     * @param createEmpId the value for entrust.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.create_emp_name
     *
     * @return the value of entrust.create_emp_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpName() {
        return createEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.create_emp_name
     *
     * @param createEmpName the value for entrust.create_emp_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpName(String createEmpName) {
        this.createEmpName = createEmpName == null ? null : createEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.create_time
     *
     * @return the value of entrust.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.create_time
     *
     * @param createTime the value for entrust.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.case_type_id
     *
     * @return the value of entrust.case_type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseTypeId() {
        return caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.case_type_id
     *
     * @param caseTypeId the value for entrust.case_type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseTypeId(String caseTypeId) {
        this.caseTypeId = caseTypeId == null ? null : caseTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.product_name
     *
     * @return the value of entrust.product_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.product_name
     *
     * @param productName the value for entrust.product_name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.remark
     *
     * @return the value of entrust.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.remark
     *
     * @param remark the value for entrust.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}