package com.atguigu.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Phone_record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.contact
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.con_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String conType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.pr_pa_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Long prPaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.pr_cat
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String prCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.collec_state_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String collecStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.negotiation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String negotiation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.pr_cc_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Long prCcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.call_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Long callId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.ptp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date ptpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.ptp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private BigDecimal ptpMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.cp_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String cpState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_record.content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.id
     *
     * @return the value of phone_record.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.id
     *
     * @param id the value for phone_record.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.type_id
     *
     * @return the value of phone_record.type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.type_id
     *
     * @param typeId the value for phone_record.type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.contact
     *
     * @return the value of phone_record.contact
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.contact
     *
     * @param contact the value for phone_record.contact
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.case_id
     *
     * @return the value of phone_record.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.case_id
     *
     * @param caseId the value for phone_record.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.con_type
     *
     * @return the value of phone_record.con_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getConType() {
        return conType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.con_type
     *
     * @param conType the value for phone_record.con_type
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setConType(String conType) {
        this.conType = conType == null ? null : conType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.pr_pa_id
     *
     * @return the value of phone_record.pr_pa_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Long getPrPaId() {
        return prPaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.pr_pa_id
     *
     * @param prPaId the value for phone_record.pr_pa_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPrPaId(Long prPaId) {
        this.prPaId = prPaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.name
     *
     * @return the value of phone_record.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.name
     *
     * @param name the value for phone_record.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.pr_cat
     *
     * @return the value of phone_record.pr_cat
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPrCat() {
        return prCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.pr_cat
     *
     * @param prCat the value for phone_record.pr_cat
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPrCat(String prCat) {
        this.prCat = prCat == null ? null : prCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.relation
     *
     * @return the value of phone_record.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.relation
     *
     * @param relation the value for phone_record.relation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.collec_state_id
     *
     * @return the value of phone_record.collec_state_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCollecStateId() {
        return collecStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.collec_state_id
     *
     * @param collecStateId the value for phone_record.collec_state_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCollecStateId(String collecStateId) {
        this.collecStateId = collecStateId == null ? null : collecStateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.negotiation
     *
     * @return the value of phone_record.negotiation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getNegotiation() {
        return negotiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.negotiation
     *
     * @param negotiation the value for phone_record.negotiation
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setNegotiation(String negotiation) {
        this.negotiation = negotiation == null ? null : negotiation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.pr_cc_id
     *
     * @return the value of phone_record.pr_cc_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Long getPrCcId() {
        return prCcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.pr_cc_id
     *
     * @param prCcId the value for phone_record.pr_cc_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPrCcId(Long prCcId) {
        this.prCcId = prCcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.call_id
     *
     * @return the value of phone_record.call_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Long getCallId() {
        return callId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.call_id
     *
     * @param callId the value for phone_record.call_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCallId(Long callId) {
        this.callId = callId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.create_emp_id
     *
     * @return the value of phone_record.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.create_emp_id
     *
     * @param createEmpId the value for phone_record.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.create_time
     *
     * @return the value of phone_record.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.create_time
     *
     * @param createTime the value for phone_record.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.ptp_time
     *
     * @return the value of phone_record.ptp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getPtpTime() {
        return ptpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.ptp_time
     *
     * @param ptpTime the value for phone_record.ptp_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPtpTime(Date ptpTime) {
        this.ptpTime = ptpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.ptp_money
     *
     * @return the value of phone_record.ptp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public BigDecimal getPtpMoney() {
        return ptpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.ptp_money
     *
     * @param ptpMoney the value for phone_record.ptp_money
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPtpMoney(BigDecimal ptpMoney) {
        this.ptpMoney = ptpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.cp_state
     *
     * @return the value of phone_record.cp_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCpState() {
        return cpState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.cp_state
     *
     * @param cpState the value for phone_record.cp_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCpState(String cpState) {
        this.cpState = cpState == null ? null : cpState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_record.content
     *
     * @return the value of phone_record.content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_record.content
     *
     * @param content the value for phone_record.content
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}