package com.atguigu.bean;

import java.util.Date;

public class Sys_dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_key
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String dictKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.value
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.order_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.parent_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.path
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.id
     *
     * @return the value of sys_dictionary.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.id
     *
     * @param id the value for sys_dictionary.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.create_time
     *
     * @return the value of sys_dictionary.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.create_time
     *
     * @param createTime the value for sys_dictionary.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.modify_time
     *
     * @return the value of sys_dictionary.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.modify_time
     *
     * @param modifyTime the value for sys_dictionary.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.version
     *
     * @return the value of sys_dictionary.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.version
     *
     * @param version the value for sys_dictionary.version
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.status
     *
     * @return the value of sys_dictionary.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.status
     *
     * @param status the value for sys_dictionary.status
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.name
     *
     * @return the value of sys_dictionary.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.name
     *
     * @param name the value for sys_dictionary.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dict_key
     *
     * @return the value of sys_dictionary.dict_key
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dict_key
     *
     * @param dictKey the value for sys_dictionary.dict_key
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey == null ? null : dictKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.value
     *
     * @return the value of sys_dictionary.value
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.value
     *
     * @param value the value for sys_dictionary.value
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.remark
     *
     * @return the value of sys_dictionary.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.remark
     *
     * @param remark the value for sys_dictionary.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.order_no
     *
     * @return the value of sys_dictionary.order_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.order_no
     *
     * @param orderNo the value for sys_dictionary.order_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.parent_id
     *
     * @return the value of sys_dictionary.parent_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.parent_id
     *
     * @param parentId the value for sys_dictionary.parent_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.path
     *
     * @return the value of sys_dictionary.path
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.path
     *
     * @param path the value for sys_dictionary.path
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}