package com.atguigu.bean;

import java.util.Date;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.grop_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String gropNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String modifyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.sys_column_ids
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String sysColumnIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.id
     *
     * @param id the value for template.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.name
     *
     * @return the value of template.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.name
     *
     * @param name the value for template.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.grop_no
     *
     * @return the value of template.grop_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getGropNo() {
        return gropNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.grop_no
     *
     * @param gropNo the value for template.grop_no
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setGropNo(String gropNo) {
        this.gropNo = gropNo == null ? null : gropNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.state
     *
     * @return the value of template.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.state
     *
     * @param state the value for template.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.create_emp_id
     *
     * @return the value of template.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.create_emp_id
     *
     * @param createEmpId the value for template.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.create_time
     *
     * @return the value of template.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.create_time
     *
     * @param createTime the value for template.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.modify_emp_id
     *
     * @return the value of template.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.modify_emp_id
     *
     * @param modifyEmpId the value for template.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyEmpId(String modifyEmpId) {
        this.modifyEmpId = modifyEmpId == null ? null : modifyEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.modify_time
     *
     * @return the value of template.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.modify_time
     *
     * @param modifyTime the value for template.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.sys_column_ids
     *
     * @return the value of template.sys_column_ids
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSysColumnIds() {
        return sysColumnIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.sys_column_ids
     *
     * @param sysColumnIds the value for template.sys_column_ids
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSysColumnIds(String sysColumnIds) {
        this.sysColumnIds = sysColumnIds == null ? null : sysColumnIds.trim();
    }
}