package com.atguigu.bean;

import java.util.Date;

public class Visit_record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.address_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.num
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.area_id1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String areaId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.area_id2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String areaId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.area_id3
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String areaId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.reason_type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String reasonTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.age
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.approve_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer approveState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.visit_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.back_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date backTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.visit_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String visitUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.visit_user_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String visitUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.apply_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String applyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.apply_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.is_effective
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String isEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.actual_visit_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Date actualVisitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.visit_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private Integer visitState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String require;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.apply_reason
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String applyReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.approve_opinion
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String approveOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.visit_report
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String visitReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_record.visit_address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    private String visitAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.id
     *
     * @return the value of visit_record.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.id
     *
     * @param id the value for visit_record.id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.state
     *
     * @return the value of visit_record.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.state
     *
     * @param state the value for visit_record.state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.address_id
     *
     * @return the value of visit_record.address_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.address_id
     *
     * @param addressId the value for visit_record.address_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.case_id
     *
     * @return the value of visit_record.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.case_id
     *
     * @param caseId the value for visit_record.case_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.num
     *
     * @return the value of visit_record.num
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.num
     *
     * @param num the value for visit_record.num
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.area_id1
     *
     * @return the value of visit_record.area_id1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAreaId1() {
        return areaId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.area_id1
     *
     * @param areaId1 the value for visit_record.area_id1
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAreaId1(String areaId1) {
        this.areaId1 = areaId1 == null ? null : areaId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.area_id2
     *
     * @return the value of visit_record.area_id2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAreaId2() {
        return areaId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.area_id2
     *
     * @param areaId2 the value for visit_record.area_id2
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAreaId2(String areaId2) {
        this.areaId2 = areaId2 == null ? null : areaId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.area_id3
     *
     * @return the value of visit_record.area_id3
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getAreaId3() {
        return areaId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.area_id3
     *
     * @param areaId3 the value for visit_record.area_id3
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAreaId3(String areaId3) {
        this.areaId3 = areaId3 == null ? null : areaId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.reason_type_id
     *
     * @return the value of visit_record.reason_type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getReasonTypeId() {
        return reasonTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.reason_type_id
     *
     * @param reasonTypeId the value for visit_record.reason_type_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setReasonTypeId(String reasonTypeId) {
        this.reasonTypeId = reasonTypeId == null ? null : reasonTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.name
     *
     * @return the value of visit_record.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.name
     *
     * @param name the value for visit_record.name
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.sex
     *
     * @return the value of visit_record.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.sex
     *
     * @param sex the value for visit_record.sex
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.age
     *
     * @return the value of visit_record.age
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.age
     *
     * @param age the value for visit_record.age
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.approve_state
     *
     * @return the value of visit_record.approve_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getApproveState() {
        return approveState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.approve_state
     *
     * @param approveState the value for visit_record.approve_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApproveState(Integer approveState) {
        this.approveState = approveState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.visit_time
     *
     * @return the value of visit_record.visit_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.visit_time
     *
     * @param visitTime the value for visit_record.visit_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.back_time
     *
     * @return the value of visit_record.back_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.back_time
     *
     * @param backTime the value for visit_record.back_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setBackTime(Date backTime) {
        this.backTime = backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.visit_user
     *
     * @return the value of visit_record.visit_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getVisitUser() {
        return visitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.visit_user
     *
     * @param visitUser the value for visit_record.visit_user
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisitUser(String visitUser) {
        this.visitUser = visitUser == null ? null : visitUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.visit_user_id
     *
     * @return the value of visit_record.visit_user_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getVisitUserId() {
        return visitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.visit_user_id
     *
     * @param visitUserId the value for visit_record.visit_user_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisitUserId(String visitUserId) {
        this.visitUserId = visitUserId == null ? null : visitUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.create_emp_id
     *
     * @return the value of visit_record.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.create_emp_id
     *
     * @param createEmpId the value for visit_record.create_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.create_time
     *
     * @return the value of visit_record.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.create_time
     *
     * @param createTime the value for visit_record.create_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.apply_emp_id
     *
     * @return the value of visit_record.apply_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApplyEmpId() {
        return applyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.apply_emp_id
     *
     * @param applyEmpId the value for visit_record.apply_emp_id
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyEmpId(String applyEmpId) {
        this.applyEmpId = applyEmpId == null ? null : applyEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.apply_time
     *
     * @return the value of visit_record.apply_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.apply_time
     *
     * @param applyTime the value for visit_record.apply_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.is_effective
     *
     * @return the value of visit_record.is_effective
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.is_effective
     *
     * @param isEffective the value for visit_record.is_effective
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setIsEffective(String isEffective) {
        this.isEffective = isEffective == null ? null : isEffective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.modify_time
     *
     * @return the value of visit_record.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.modify_time
     *
     * @param modifyTime the value for visit_record.modify_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.actual_visit_time
     *
     * @return the value of visit_record.actual_visit_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Date getActualVisitTime() {
        return actualVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.actual_visit_time
     *
     * @param actualVisitTime the value for visit_record.actual_visit_time
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setActualVisitTime(Date actualVisitTime) {
        this.actualVisitTime = actualVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.visit_state
     *
     * @return the value of visit_record.visit_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public Integer getVisitState() {
        return visitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.visit_state
     *
     * @param visitState the value for visit_record.visit_state
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisitState(Integer visitState) {
        this.visitState = visitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.require
     *
     * @return the value of visit_record.require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRequire() {
        return require;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.require
     *
     * @param require the value for visit_record.require
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRequire(String require) {
        this.require = require == null ? null : require.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.apply_reason
     *
     * @return the value of visit_record.apply_reason
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.apply_reason
     *
     * @param applyReason the value for visit_record.apply_reason
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason == null ? null : applyReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.approve_opinion
     *
     * @return the value of visit_record.approve_opinion
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getApproveOpinion() {
        return approveOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.approve_opinion
     *
     * @param approveOpinion the value for visit_record.approve_opinion
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setApproveOpinion(String approveOpinion) {
        this.approveOpinion = approveOpinion == null ? null : approveOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.remark
     *
     * @return the value of visit_record.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.remark
     *
     * @param remark the value for visit_record.remark
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.visit_report
     *
     * @return the value of visit_record.visit_report
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getVisitReport() {
        return visitReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.visit_report
     *
     * @param visitReport the value for visit_record.visit_report
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisitReport(String visitReport) {
        this.visitReport = visitReport == null ? null : visitReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_record.visit_address
     *
     * @return the value of visit_record.visit_address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public String getVisitAddress() {
        return visitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_record.visit_address
     *
     * @param visitAddress the value for visit_record.visit_address
     *
     * @mbggenerated Sat Apr 21 09:54:16 CST 2018
     */
    public void setVisitAddress(String visitAddress) {
        this.visitAddress = visitAddress == null ? null : visitAddress.trim();
    }
}